services:
  chromadb:
    image: chromadb/chroma:latest
    ports:
      - "8000:8000"
    volumes:
      - chroma_data:/chroma/chroma
    environment:
      - CHROMA_SERVER_HOST=0.0.0.0
      - CHROMA_SERVER_HTTP_PORT=8000

  preprocessor:
    build:
      context: .
      dockerfile: scripts/preprocessor.Dockerfile
    depends_on:
      - chromadb
    environment:
      - CHROMA_HOST=chromadb
      - CHROMA_PORT=8000
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - ./local:/app/local:ro
      - ./logs:/app/logs
    restart: "no"

  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    ports:
      - "8001:8000"
    depends_on:
      - chromadb
      - preprocessor
    environment:
      - CHROMA_HOST=chromadb
      - CHROMA_PORT=8000
      - ENVIRONMENT=production
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - ./logs:/app/logs

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_BACKEND_URL: https://meddoc.fly.dev
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  chroma_data:
